//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkdownEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkdownEditor.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;cell&gt;((?&lt;=\|\s*){content}(?=\s*\|))|((?&lt;head&gt;\#{1,}\s*){content})).
        /// </summary>
        internal static string rxColumnMapReplacement {
            get {
                return ResourceManager.GetString("rxColumnMapReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:\s*(?&lt;name&gt;[^\:\;]+)\s*\:\s*(?&lt;value&gt;[^\;]+)\s*).
        /// </summary>
        internal static string rxCssNameValue {
            get {
                return ResourceManager.GetString("rxCssNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^(?&lt;stylename&gt;sectionbackgroundcoloreven)$).
        /// </summary>
        internal static string rxDocStyleSectionBackEven {
            get {
                return ResourceManager.GetString("rxDocStyleSectionBackEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^(?&lt;stylename&gt;sectionbackgroundcolor(?&lt;evenodd&gt;(even|odd)))$).
        /// </summary>
        internal static string rxDocStyleSectionBackEvenOdd {
            get {
                return ResourceManager.GetString("rxDocStyleSectionBackEvenOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^(?&lt;stylename&gt;sectionbackgroundcolorodd)$).
        /// </summary>
        internal static string rxDocStyleSectionBackOdd {
            get {
                return ResourceManager.GetString("rxDocStyleSectionBackOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;filename&gt;[^\.]+)(?&lt;extension&gt;(\.[^\.]+)*).
        /// </summary>
        internal static string rxFilenameAndExtension {
            get {
                return ResourceManager.GetString("rxFilenameAndExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;folder&gt;([a-z]+\:(//){0,1}|\\\\\w+|[^\\/]+))).
        /// </summary>
        internal static string rxFolderElement {
            get {
                return ResourceManager.GetString("rxFolderElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?&lt;heading&gt;\&lt;h(?&lt;digit&gt;\d)(\s+(?&lt;attributes&gt;[^\&gt;]*)){0,1}\&gt;\s*(?&lt;content&gt;[^\&lt;]*)\s*\&lt;/h\k&lt;digit&gt;\&gt;)).
        /// </summary>
        internal static string rxHtmlHeading {
            get {
                return ResourceManager.GetString("rxHtmlHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?&lt;heading&gt;\&lt;h(?&lt;digit&gt;\d)(?&lt;attributes&gt;[^\&gt;]*)\&gt;(?!\s*\&lt;font[^\&gt;]*\&gt;)\s*(?&lt;content&gt;.*?)\s*(?&lt;!\&lt;/font\&gt;\s*)\&lt;/h\k&lt;digit&gt;\&gt;)).
        /// </summary>
        internal static string rxHtmlHeadingNoFont {
            get {
                return ResourceManager.GetString("rxHtmlHeadingNoFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;hexcolor&gt;\#(?&lt;r&gt;[0-9a-f]{2})(?&lt;g&gt;[0-9a-f]{2})(?&lt;b&gt;[0-9a-f]{2})(?&lt;a&gt;[0-9a-f]{2}){0,1})).
        /// </summary>
        internal static string rxHtmlHexColor {
            get {
                return ResourceManager.GetString("rxHtmlHexColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?&lt;cell&gt;\&lt;t(?&lt;celltype&gt;d|h)(?&lt;attributes&gt;[^\&gt;]*)\&gt;(?!\s*\&lt;font[^\&gt;]*\&gt;)\s*(?&lt;content&gt;.*?)\s*(?&lt;!\&lt;/font\&gt;\s*)\&lt;/t\k&lt;celltype&gt;\&gt;)).
        /// </summary>
        internal static string rxHtmlTableCellNoFont {
            get {
                return ResourceManager.GetString("rxHtmlTableCellNoFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:\&lt;table[^\&gt;]*\&gt;\s*\&lt;tr[^\&gt;]*\&gt;\s*(?&lt;firstrow&gt;(\&lt;t(?&lt;celltype&gt;d|h)[^\&gt;]*\&gt;.*?\&lt;/t\k&lt;celltype&gt;\&gt;)+)\s*\&lt;/tr\&gt;).
        /// </summary>
        internal static string rxHtmlTableFirstRow {
            get {
                return ResourceManager.GetString("rxHtmlTableFirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:{(?&lt;variable&gt;\w+[^}]*)}).
        /// </summary>
        internal static string rxInterpolatedExpression {
            get {
                return ResourceManager.GetString("rxInterpolatedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?&lt;line&gt;[^\r\n]*)(\r{0,1}\n|$)).
        /// </summary>
        internal static string rxLine {
            get {
                return ResourceManager.GetString("rxLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:^[\t ]{0,3}(?&lt;level&gt;\#+)[\t ]+(?&lt;line&gt;.*)$).
        /// </summary>
        internal static string rxMarkdownHeading {
            get {
                return ResourceManager.GetString("rxMarkdownHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?&lt;level&gt;\#{1,9})[\t ]+(?!\&lt;font[^\&gt;]*\&gt;)(?&lt;content&gt;[^\r\n]+)(?!\&lt;/font\&gt;)).
        /// </summary>
        internal static string rxMarkdownHeadingLevelContentNoFont {
            get {
                return ResourceManager.GetString("rxMarkdownHeadingLevelContentNoFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:^[\t ]{0,3}(?&lt;level&gt;\#{{minLevel},{maxLevel}})[\t ]+(?&lt;line&gt;.*)$).
        /// </summary>
        internal static string rxMarkdownHeadingN {
            get {
                return ResourceManager.GetString("rxMarkdownHeadingN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:^(?&lt;prefix&gt;[\t ]{0,3})(?&lt;level&gt;\#+)[\t ]+(?!\s*\&lt;font[^\&gt;]*\&gt;)\s*(?&lt;line&gt;.*)$(?&lt;!\&lt;/font\&gt;\s*)).
        /// </summary>
        internal static string rxMarkdownHeadingNoFont {
            get {
                return ResourceManager.GetString("rxMarkdownHeadingNoFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:(?i:^(?&lt;line&gt;\s*\&lt;.*)$)).
        /// </summary>
        internal static string rxMarkdownHtmlLine {
            get {
                return ResourceManager.GetString("rxMarkdownHtmlLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?&lt;line&gt;(?&lt;=[\r\n]*)[\t ]*---(?=[\r\n]+))).
        /// </summary>
        internal static string rxMarkdownLine {
            get {
                return ResourceManager.GetString("rxMarkdownLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:^(?&lt;line&gt;[\t ]*---)\s*$).
        /// </summary>
        internal static string rxMarkdownLinePart {
            get {
                return ResourceManager.GetString("rxMarkdownLinePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:^(?&lt;listItem&gt;(?&lt;leadingSpace&gt;[\t ]*)(?&lt;listType&gt;-|[0-9a-zA-Z]+\.)[\t ]{1,4}(?&lt;text&gt;.*))$).
        /// </summary>
        internal static string rxMarkdownListItem {
            get {
                return ResourceManager.GetString("rxMarkdownListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?&lt;=\|\s+)(?!\&lt;font[^\&gt;]*\&gt;)(?&lt;content&gt;[^\|]+)(?!\&lt;/font\&gt;)(?=\s+\|)).
        /// </summary>
        internal static string rxMarkdownTableCellNoFont {
            get {
                return ResourceManager.GetString("rxMarkdownTableCellNoFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:^(?&lt;row&gt;(?&lt;prefix&gt;[\t ]*)(?&lt;content&gt;\|.*\|))\s*$).
        /// </summary>
        internal static string rxMarkdownTableRow {
            get {
                return ResourceManager.GetString("rxMarkdownTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:^(?&lt;listItem&gt;(?&lt;leadingSpace&gt;[\t ]*)-[\t ]{1,4}(?&lt;text&gt;.*))$).
        /// </summary>
        internal static string rxMarkdownUListItem {
            get {
                return ResourceManager.GetString("rxMarkdownUListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:%(?&lt;variable&gt;\w+[^%]*)%).
        /// </summary>
        internal static string rxParameterExpression {
            get {
                return ResourceManager.GetString("rxParameterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?s:(?&lt;section&gt;\&lt;section\s*[^\&gt;]*(number\s*=\s*\&quot;(?&lt;sectionNumber&gt;[^\&quot;]*)\&quot;){0,1}\s*\&gt;\s*(?&lt;content&gt;.*?)\s*\&lt;/section\&gt;)).
        /// </summary>
        internal static string rxSection {
            get {
                return ResourceManager.GetString("rxSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:^[\t ]*(?&lt;element&gt;\&lt;/section\&gt;)\s*$).
        /// </summary>
        internal static string rxSectionEnd {
            get {
                return ResourceManager.GetString("rxSectionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:^[\t ]*(?&lt;element&gt;\&lt;section)\s*).
        /// </summary>
        internal static string rxSectionStart {
            get {
                return ResourceManager.GetString("rxSectionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;name&gt;H(?&lt;digit&gt;\d)FontColor)).
        /// </summary>
        internal static string rxStyleHxFontColor {
            get {
                return ResourceManager.GetString("rxStyleHxFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;name&gt;H(?&lt;digit&gt;\d)FontName)).
        /// </summary>
        internal static string rxStyleHxFontName {
            get {
                return ResourceManager.GetString("rxStyleHxFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;name&gt;H(?&lt;digit&gt;\d)FontSize)).
        /// </summary>
        internal static string rxStyleHxFontSize {
            get {
                return ResourceManager.GetString("rxStyleHxFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:(?i:^(?&lt;headtype&gt;H(\d|eading)))).
        /// </summary>
        internal static string rxStyleHxType {
            get {
                return ResourceManager.GetString("rxStyleHxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:(?i:^(?&lt;styletype&gt;TableHeader))).
        /// </summary>
        internal static string rxStyleTableHeaderType {
            get {
                return ResourceManager.GetString("rxStyleTableHeaderType", resourceCulture);
            }
        }
    }
}
